services:
  redis:
    image: redis:6.0.7
    # container_name: redis
    # hostname: redis
    ports:
      - 6379:6379
    volumes:
      - ./volumes/redis/data:/data
    command: redis-server
    restart: unless-stopped

  redisinsight:
    image: redislabs/redisinsight:latest
    # container_name: redisinsight
    # hostname: redisinsight
    ports:
      - 8001:8001
    volumes:
      - ./volumes/redisinsight:/db
    restart: unless-stopped

  app:
    image: node:16-bullseye
    volumes:
      - ./src:/app
    working_dir: /app
    command: sleep infinity
    restart: unless-stopped
