services:
  redis:
    image: redis:6.0.7
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
    volumes:
      - ./volumes/redis/etc_redis:/etc/redis
      - ./volumes/redis/data:/data
    command: redis-server /etc/redis/redis.conf
    restart: always

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    hostname: redisinsight
    ports:
      - 8001:8001
    volumes:
      - redisinsight_store:/db
    restart: always

volumes:
  redisinsight_store:
