services:
  test_host:
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
      # - '.:/home/myuser/app'
      # - node_modules:/home/myuser/app/node_modules

    # working_dir: ./app
    command: sleep infinity

    #   - './tests_host/screenshots:/screenshots'
    # # command: "wait-for-it.sh react_host_client:3000 && \
    # #   -- mocha --recursive /integration-tests"
    # command: >
    #   bash -c "wait-for-it.sh react_host_client:3000 &&
    #   wait-for-it.sh react_host_cms:3000 &&
    #   wait-for-it.sh react_host_admin:3000 -- mocha --recursive /integration-tests"
    # depends_on:
    #   - react_host_client

# volumes:
  # node_modules:
