# CREDIT: https://github.com/shren207/nextjs-docker-compose
services:
  backend:
    build: .
    ports:
      - 3000:3000
      - 5555:5555
    working_dir: /app
    volumes:
      - $PWD:/app
      - be_node_modules:/app/node_modules
    command: sleep infinity

volumes:
  be_node_modules:
