services:
  mongo:
    image: mongo:latest
    # container_name: mongo
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongo/data/db:/data/db
      - ./volumes/mongo/data/configdb:/data/configdb

  mongo-express:
    image: mongo-express:latest
    # container_name: mongo-express
    environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      # ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: '27017'
    ports:
      - 8081:8081
    depends_on:
      - mongo

  redis:
    image: redis:6.0.7
    # container_name: redis
    # hostname: redis
    ports:
      - 6379:6379
    volumes:
      - ./volumes/redis/etc_redis:/etc/redis
      - ./volumes/redis/data:/data
    command: redis-server /etc/redis/redis.conf
    restart: always

  redisinsight:
    image: redislabs/redisinsight:latest
    # container_name: redisinsight
    # hostname: redisinsight
    ports:
      - 8001:8001
    volumes:
      - redisinsight_store:/db
    restart: always

  dbapi:
    build: ./src/dbapi
    ports:
      - 3001:3001
    volumes:
      - ./src/dbapi:/app
    depends_on:
      - mongo

  kue-scheduler-api:
    build: ./src/kue-scheduler-api
    ports:
      - 3002:3002
    volumes:
      - ./src/kue-scheduler-api:/app
    depends_on:
      - mongo
      - redis
    # command: sleep infinity

volumes:
  redisinsight_store:
